language: node_js
branches:
  only:
  - gh-pages
  - /.*/
node_js:
  - 9
  - 8
script: echo "Running tests against $(node -v) ..." 
jobs:
 include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to github ..."
      deploy:
        provider: releases
        api_key: "$GITHUB_API_KEY"
        skip_cleanup: true
        on:
          tags: true
    - stage: NPM Release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: "$NPM_API_KEY"
      email: "Charles.Heath.Berman@gmail.com"
      on: deploy-npm-release
notifications:
  email:
    on_success: always


 